export const DOLLAR_PRICE_REQUEST = "DOLLAR_PRICE_REQUEST";
export const DOLLAR_PRICE_SUCCESS = "DOLLAR_PRICE_SUCCESS";
export const DOLLAR_PRICE_FIALD = "DOLLAR_PRICE_FIALD";

export const BUY_ORDER_REQUEST = "BUY_ORDER_REQUEST";
export const BUY_ORDER_SUCCESS = "BUY_ORDER_SUCCESS";
export const BUY_ORDER_FIALD = "BUY_ORDER_FIALD";

export const SELL_ORDER_REQUEST = "SELL_ORDER_REQUEST";
export const SELL_ORDER_SUCCESS = "SELL_ORDER_SUCCESS";
export const SELL_ORDER_FIALD = "SELL_ORDER_FIALD";

export const BUY_ORDERS_STATUS_REQUEST = "BUY_ORDERS_STATUS_REQUEST";
export const BUY_ORDERS_STATUS_SUCCESS = "BUY_ORDERS_STATUS_SUCCESS";
export const BUY_ORDERS_STATUS_FIALD = "BUY_ORDERS_STATUS_FIALD";

export const SELL_ORDERS_STATUS_REQUEST = "SELL_ORDERS_STATUS_REQUEST";
export const SELL_ORDERS_STATUS_SUCCESS = "SELL_ORDERS_STATUS_SUCCESS";
export const SELL_ORDERS_STATUS_FIALD = "SELL_ORDERS_STATUS_FIALD";

export const CART_ORDER_REQUEST = "CART_ORDER_REQUEST";
export const CART_ORDER_SUCCESS = "CART_ORDER_SUCCESS";
export const CART_ORDER_FIALD = "CART_ORDER_FIALD";

export const TICKET_REQUEST = "TICKET_REQUEST";
export const TICKET_SUCCESS = "TICKET_SUCCESS";
export const TICKET_FIALD = "TICKET_FIALD";

export const TICKET_SEND_REQUEST = "TICKET_SEND_REQUEST";
export const TICKET_SEND_SUCCESS = "TICKET_SEND_SUCCESS";
export const TICKET_SEND_FIALD = "TICKET_SEND_FIALD";
export const TICKET_SEND_END = "TICKET_SEND_END";
