# Generated by Django 4.1.7 on 2023-04-11 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_card_num', models.IntegerField(blank=True, null=True)),
                ('bank_shaba_num', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(default='profile/avatar.png', upload_to='profile/avatar/')),
                ('selfi_image', models.ImageField(blank=True, null=True, upload_to='profile/selfi_image/')),
                ('vip_user', models.BooleanField(default=False)),
                ('selfi_image_status', models.CharField(choices=[('to do', 'To Do'), ('in progress', 'In Progress'), ('failed', 'Failed'), ('done', 'Done')], default='to do', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
