# Generated by Django 4.1.7 on 2023-04-20 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('voucher_code', models.CharField(max_length=60)),
                ('activate_code', models.CharField(max_length=60)),
                ('condition', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending'), ('created', 'Created')], default='created', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('tracking_code', models.CharField(blank=True, max_length=200, null=True)),
                ('condition', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending'), ('created', 'Created')], default='created', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
