# Generated by Django 4.1.7 on 2023-04-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField()),
                ('payment_id', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('date', models.TextField(default='-')),
                ('card_number', models.TextField(default='****')),
                ('idpay_track_id', models.BigIntegerField(default=0)),
                ('bank_track_id', models.TextField(default=0)),
                ('status', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تاریخچه پرداخت ها',
                'verbose_name_plural': 'تاریخچه پرداخت ها',
            },
        ),
    ]
