# Generated by Django 4.1.7 on 2023-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='date_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
