# Generated by Django 4.1.7 on 2023-05-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_buyorder_date_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorder',
            name='date_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
